### ISSUE TITLE
S3 upload doesn't work

### ISSUE THREAD

**Issue by nourahassan** [awslabs/aws-mobile-appsync-sdk-ios#122] opened 2018-12-04 23:53 UTC
I followed the documentation here https://aws-amplify.github.io/docs/ios/storage#usage-with-graphql-apis-complex-objects

First the code generated by `aws-appsync-codegen` has a compilation issue, it adds an extension to S3Object and  compiler complains it is not configured. There is no struct S3Object only S3ObjectInput.

I commented this code:

```
extension S3Object: AWSS3ObjectProtocol {
  public func getBucketName() -> String {
      return bucket
  }

  public func getKeyName() -> String {
      return key
  }

  public func getRegion() -> String {
      return region
  }
}
```

Then when I create my Post with the file, it saves the post to dynamoDB but not the file to S3. And there is no single error?!!

And I even added a breakpoint to created extension for AWSTransferUtilities created by the codegen and it is never called??
 
 - AppSync SDK Version: 2.7.0
 - Dependency Manager: Carthage
 - Swift Version : 4.1
 - Device:  Simulator
 - iOS Version: 12.1

**Comment by rohandubal** [comment] 2018-12-05 01:01
Hello @nourahassan 

Sorry that you are having issues using the SDK.

Could you please provide with the schema which you are using? I will try to put up a small sample which demonstrates this feature. You should not have to delete any generated code. 

Thanks,
Rohan

**Comment by kjlis** [comment] 2018-12-11 03:04
I'm experiencing exactly the same problem. In the beginning I was following [the amplify guide](https://aws-amplify.github.io/docs/cli/graphql#s3-objects) which mentions only adding `S3Object` type:
```
type S3Object {
  bucket: String!
  region: String!
  key: String!
}
```
After running `amplify push` GraphQL API gets updated, the auto-upload didn't work, so I followed the [guide from Storage section](https://aws-amplify.github.io/docs/ios/storage#usage-with-graphql-apis-complex-objects) and added 
```
type Item @model @auth(rules: [{ allow: owner }) 
{
  id: ID!
  owner: String!
  itemName: String!
  file: S3Object
}
  type S3Object {
          bucket: String!
          key: String!
          region: String!
  }
  input S3ObjectInput {
          bucket: String!
          key: String!
          region: String!
          localUri: String!
          mimeType: String!
  }
```
to `backend/api/~apiname~/schema.graphql` and regenerated the code by running:
```
amplify push &&
aws-appsync-codegen generate graphql/*.graphql --schema graphql/schema.json --output API.swift --add-s3-wrapper
```
Please note that `graphql/*.graphql` contains operations generated based on `backend/api/~apiname~/schema.graphql`. As a result, I also got compilation error stating that there is no struct S3Object only S3ObjectInput. Just like @nourahassan I commented it out, passed `AWSTransferUtilities` to AppSync configuration, tried to upload the file and the only mutation that happened was a new row in DynamoDB - no file in S3. Also, it seems like after generating the code with flag ```-add-s3-wrapper``` my DynamoDB receives `S3ObjectInput` (so with localUri and mimeType) and not S3Object (so just region, bucket and key).

**Comment by kjlis** [comment] 2018-12-14 06:09
Hi!

Is there any progress on the code example for Swift example of automatic upload to S3?I found an old issue that seems to describe the same issue: https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/45
Is it still the root cause of the problem or it's more likely due to some misconfiguration on my end?

Thanks!

**Comment by teeeg** [comment] 2019-01-03 02:51
Thank you @palpatim . Can confirm I see this fail, as you say, "where the S3Object is part of a mutation input type, rather than a direct parameter of the mutation."

**Comment by kjlis** [comment] 2019-01-06 06:59
Thanks a lot for looking into this @palpatim!

Few follow-up questions:
1. Does the download from S3 also happen automatically when running GraphQL queries? The docs seem to be missing any examples of that. If so:
    1. How can we access the downloaded file (the model stores just the S3 bucket, key etc.)
    1. Are downloaded files cached by default?
1. The docs in [Storage](https://aws-amplify.github.io/docs/ios/storage#usage-with-graphql-apis-complex-objects) and [GraphQL](https://aws-amplify.github.io/docs/cli/graphql#s3-objects) sections seem to be out of sync - I assume the ones we should follow are in the Storage section? For example, GraphQL docs don't mention updating the resolvers or running code gen with `--add-s3-wrapper`. It would be nice to have a short, end-to-end example for iOS demonstrating the feature to avoid confusion between both sections (like for ReactJS).

Thanks again for taking care of that!

**Comment by palpatim** [comment] 2019-01-10 21:38
This should be fixed on 2.9.0. Please let us know if you continue to have any problems.

@kjlis:

1. Downloads do not happen automatically. 
    1. You should be able to use a GraphQL object's field conforming to `S3ObjectProtocol` to download using the AppSyncClient's S3ObjectManager. Please see the [S3ObjectWrapper.swift](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/blob/master/AWSAppSyncTestCommon/S3ObjectWrapper.swift#L63) file in our new "TestCommon" target for a sample of how we conform AWSS3TransferUtility to S3ObjectManager protocol, and the sample implementation of `download`
    1. Download caching is not handled by the SDK.
1. Thanks for pointing out the documentation discrepancy. I'll get a bug in our doc repo to correct that!

**Comment by nourahassan** [comment] 2019-01-10 23:07
Just tried to run `carthage update` to get 2.9.0 but it fails :(

```
*** Building scheme "AWSAppSync" in AWSAppSyncClient.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /{path}/Carthage/Checkouts/aws-mobile-appsync-sdk-ios/AWSAppSyncClient.xcodeproj -scheme AWSAppSync -configuration Release -derivedDataPath /{path}/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/aws-mobile-appsync-sdk-ios/2.9.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/v5/rj2p6_yd42n726hp2j5z9y880000gp/T/aws-mobile-appsync-sdk-ios SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /{path}/Carthage/Checkouts/aws-mobile-appsync-sdk-ios)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/v5/rj2p6_yd42n726hp2j5z9y880000gp/T/carthage-xcodebuild.CPvjqH.log
```

Should that be a different issue?

**Comment by palpatim** [comment] 2019-01-11 00:47
@nourahassan Thanks for letting us know. It looks like the Carthage build failed on travis-ci as well. We're investigating.

**Comment by palpatim** [comment] 2019-01-11 03:47
@nourahassan 

We've release 2.9.1 now that should fix the problem. Please let us know if you encounter any issues.

**Comment by nourahassan** [comment] 2019-01-11 20:07
Carthage downloads the framework but gives error `Incompatible Swift version - framework was built with 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)`

But it built the schema successfully!

It still didn't upload the image to s3, only saved the object to dynamoDB. I am using the imageURL.absoluteString as the s3ObjectInput.localUri. Please tell me if I am missing something.

**Comment by palpatim** [comment] 2019-01-14 20:57
Hi @nourahassan,

It looks like you're using the binary Carthage build. We currently build the SDK with Xcode 10/Swift 4.2, which means that to consume from Carthage you'll need to use the `--no-use-binaries` flag, as in:

```bash
carthage update --platform ios --cache-builds --no-use-binaries
```

Regarding not uploading: Because you had a problem building, I wonder whether there was a problem using the SDK. I'll investigate on my side but in the meantime, can you confirm that you've updated to 2.9.1? Thanks!

**Comment by nourahassan** [comment] 2019-01-14 22:13
Yes it is 2.9.1. Attached the info.plist from `Carthage/Build/iOS/AWSAppSync.framework`
 
<img width="710" alt="screen shot 2019-01-15 at 12 10 46 am" src="https://user-images.githubusercontent.com/537740/51144545-07e3be80-185a-11e9-929d-5f72a200785f.png">

As I said Carthage did build the schema successfully.

**Comment by nourahassan** [comment] 2019-01-22 18:02
Any updates here?

**Comment by palpatim** [comment] 2019-01-22 21:02
Hi @nourahassan,

Sorry for the delay. I'm continuing to look at this and will update as soon as I have more info.

**Comment by codeslubber** [comment] 2019-02-04 22:09
Wow this is depressing.. I cannot believe:
- this doesn't work
- it's taking this long to get this to work
The whole point of this framework goes right out the window when broken windows like this are left uh, broken.

**Comment by palpatim** [comment] 2019-02-04 23:36
Sorry for the continued delay on this--we're working on some crashes on this and other iOS SDKs, but it is next on the list to be worked on.

**Comment by palpatim** [comment] 2019-02-11 17:48
Hi @nourahassan,

I've been unable to replicate this either in local testing or in integration tests that I added as part of #174. I will note that the setup is non-intuitive, since it involves going to the JS area of the documentation, but once I set up the buckets, policies, and local clients, S3 uploads work using both parameterized and input-ized mutations.

Can you provide any more details around your use cases that are failing?

**Comment by palpatim** [comment] 2019-02-12 22:01
Hi @nourahassan 

As discussed separately, we were able to confirm that S3 uploads are working for you as expected. I'm going to close this issue, but if you find any other issues with the AppSync SDK, feel free to open a new one.

Separately, given the problems we had getting your Carthage-based project set up for debugging the AppSync client, we will take on a task to improve our documentation around that flow.

Thanks again for your patience.

**Closed by palpatim** 2019-02-12 22:01 UTC
Labels: AppSync, Bug, Investigating
