### ISSUE TITLE
[FeatureRequest]Codegen for AppSync - Support objects with multiple S3Object types

### ISSUE THREAD

**Issue by yunfei356** [awslabs/aws-mobile-appsync-sdk-ios#116] opened 2018-12-01 04:01 UTC
**Describe the bug**
I ran amplify codegen on my AppSync API and it generated API.swift and the GraphQL folder with mutations, queries, subscriptions, and schema.json. However, I noticed that the downloaded schema is missing one of the fields. Specifically, I have the following type:

```
type ProfileBase {
	name: String!
	email: AWSEmail!
	phone: AWSPhone
	location_coords: [Float]!
	location: String!
	profilePicture: S3Object
	otherPictures: [S3Object]
	selfIntro: String
	birthdate: AWSDate
	isFemale: Boolean
}
```
But the generated code is missing the profilePicture field. I heard from one other person that he/she is also experiencing this issue. I thought I'd submit a bug here so you can better track it, if it's indeed a bug. I moved the API into my project, and as expected, the compiler cannot find the field profilePicture.

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.7.0
 - Dependency Manager: CocoaPods
 - Swift Version : 4.2

**Comment by rohandubal** [comment] 2018-12-05 01:02
Hello @yunfei356 

Having multiple S3Object as part of object is currently not supported. If you only use the `profilePicture` field, you should be able to use the data type. I will take this as a feature request to the team for prioritization.

Thank you,
Rohan

**Comment by palpatim** [comment] 2019-01-21 16:11
Dupe of #116. Closing so we can track the feature request on that issue.

**Closed by palpatim** 2019-01-21 16:11 UTC
Labels: AppSync, feature request
