### ISSUE TITLE
federatedSignIn and unauthorized requests

### ISSUE THREAD

**Issue by bananita** [awslabs/aws-mobile-appsync-sdk-ios#307] opened 2019-10-16 21:52 UTC
Hello, I am trying to implement federated signIn using AppSync. I create everything as described in documentation, but for some unknown reasons I still can't send requests with app sync.

I create stack using snippet:
```
let cacheConfiguration = try? AWSAppSyncCacheConfiguration()

let appSyncServiceConfig = try? AWSAppSyncServiceConfig()
let appSyncConfig = try? AWSAppSyncClientConfiguration(
            appSyncServiceConfig: AWSAppSyncServiceConfig(),
            userPoolsAuthProvider: MyCognitoUserPoolsAuthProvider(),
            cacheConfiguration: cacheConfiguration)
             
appSyncClient = try? AWSAppSyncClient(appSyncConfig: appSyncConfig!)
```
using standard implementation of **MyCognitoUserPoolsAuthProvider**:
```
class MyCognitoUserPoolsAuthProvider: AWSCognitoUserPoolsAuthProviderAsync {
    func getLatestAuthToken(_ callback: @escaping (String?, Error?) -> Void) {
        AWSMobileClient.sharedInstance().getTokens { (tokens, error) in
            if error != nil {
                callback(nil, error)
            } else {
                callback(tokens?.idToken?.tokenString, nil)
            }
        }
    }
}
```
Next, I register: (**result.token** and **result.identityId** are provided by my backend)
```
 AWSMobileClient.sharedInstance().federatedSignIn(
                providerName: IdentityProvider.developer.rawValue,
                token: result.token,
                federatedSignInOptions: FederatedSignInOptions(cognitoIdentityId: result.identityId)) { (userState, error) in
                    if let error = error as? AWSMobileClientError {
                        print(error.localizedDescription)
                    }
                    if let userState = userState {
                        print("Status: \(userState.rawValue)")
                    }
            }
```
which results with `userState == signedIn`. Every app sync request is finishing with unauthorized error. I've created breakpoint inside `MyCognitoUserPoolsAuthProvider`, where I saw that `AWSMobileClient.sharedInstance().getTokens` always results with empty token and error. I've also tried to use alternative implementation of this class. It is returning token created by my backend, but I also get unauthorized error:
```
class MyCognitoUserPoolsAuthProvider: AWSCognitoUserPoolsAuthProviderAsync {
    func getLatestAuthToken(_ callback: @escaping (String?, Error?) -> Void) {
        AWSMobileClient.sharedInstance().logins().continueWith { (result) -> Any? in
            callback(result.result?["cognito-identity.amazonaws.com"] as? String, nil)
            return nil
        }
    }
}
```
I currently have no idea what I'm doing wrong and how can I fix my problem. Can anybody help me solve it?

**Which AWS Services are you utilizing?**
AWSMobileClient, AWSAppSync

**Environment(please complete the following information):**
 - AWSAppSync [2.14.2]
 - AWSMobileClient [2.10.2]
 - Dependency Manager: Cocoapods
 - Swift Version: 5.1

**Device Information (please complete the following information):**
 - Device: [iPhone XR Simulator]
 - iOS Version: [iOS 13]
 - Specific to simulators: no

**Comment by palpatim** [comment] 2019-10-18 14:12
Dupe of https://github.com/aws-amplify/aws-sdk-ios/issues/1996. Closing this in favor of that one.

**Closed by palpatim** 2019-10-18 14:12 UTC
Labels: AppSync, Question
