### ISSUE TITLE
Subscription Fail Event Trigger

### ISSUE THREAD

**Issue by vishaldroisys** [awslabs/aws-mobile-appsync-sdk-ios#392] opened 2020-06-10 10:42 UTC
**Describe the bug**
Hi We are working on an iPad application and using the AppSync for the offline support, we are having an issue if the device goes offline and comes online then subscription is not working and no any new record is coming to the device. can we handle(Trigger) subscription failed event??

**Expected behavior**
If subscription failed then we can re-start subscription either automatically or manually.

**Device Information (please complete the following information):**
 - Device: iPhone6, Simulator
 - iOS Version: iOS 13

Thanks in advanced.

**Comment by wooj2** [comment] 2020-06-24 02:44
Hi @vishaldroisys,

Sounds like if I were to re-word your problem, it would be:
"When a device moves from an offline to online state, subscription connections are not reconnected."

This seems contrary to the issue you posted [here](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/393), where you are disconnecting a device from wifi, and then reconnecting the wifi, in which case, you are seeing a `.connected` state in the `statusChangeHandler`.  For your device to receive updates on a subscription, you must at least be in a `.connected` state.

Can you please explain what you mean by "subscription is not working"?

**Comment by vishaldroisys** [comment] 2020-06-24 11:47
After Disconnecting, user will not get any new subscription event until we re-initialise the subscription.
Thanks.

**Comment by wooj2** [comment] 2020-06-24 16:57
You mentioned, "until we re-initialize the subscription" -- are you having to call `cancel()` on the watcher, and then re-initialize the subscription after you have disconnected from wifi and then reconnected to wifi?  If so, this is not expected behavior.  If you turn off your wifi, the websocket connection will be disconnected, but you are still in a subscribed state.  When you turn on your wifi, the websocket connection will attempt to re-connect, and the subscription will attempt to re-establish itself.

A couple things to note during the interaction described above:
During the time you are offline (e.g. turning wifi off), there are no guarantees around receiving updates (because you are offline)
When you come online (e.g. turning wifi on), you will not receive any updates on the subscription while you were offline.

**Comment by vishaldroisys** [comment] 2020-06-24 17:01
@wooj2 we have not used cancel() right now. but can you tell me if we are in offline and in offline mode if we call Cancel() then it will work properly??

second thing if we call cancel() and user will come from offline to online then we are initializing all subscription again.

Thanks in advance.

**Comment by wooj2** [comment] 2020-06-24 17:14
If you call `cancel()` on the watcher, the intended behavior is that:
1. You will no longer get updates for that model
2. You will receive a `.disconnected` on the `statusChangeHandler` callback -- (however, due to a bug, you will not get this callback.)

When you say: "second thing if we call cancel() and user will come from offline to online then we are initializing all subscription again."  I don't understand what you are saying.  Would you be able to provide some code which demonstrates this?

**Comment by vishaldroisys** [comment] 2020-06-24 17:20
@wooj2 when we goes to offline then we call Cancel()

and then we come to online and calling subscription again.

Thanks.

**Comment by wooj2** [comment] 2020-06-24 17:34
Sure, that can be one approach to managing your subscription, but I don't believe that is the intended design of AppSync, because the AppSyncRealTimeClient's responsibility is to listen for keep alive messages and automatically reconnect the socket/subscription if there is a disconnect/missing keep alive.  That being said, if it works for your use case, that is up to you.

More information on this interaction can be found here:
https://docs.aws.amazon.com/appsync/latest/devguide/real-time-websocket-client.html

That being said, having to manage outgoing mutations along with subscriptions is not an easy task.  This is largely why we created Amplify DataStore.  Based on the complexity you are experiencing, we highly recommend you looking at DataStore:
https://docs.amplify.aws/lib/datastore/getting-started/q/platform/ios
https://www.youtube.com/watch?v=KcYl6_We0EU

I will be optimistically closing this ticket, but feel free to re-open or comment if you have additional questions regarding this topic.

**Comment by vishaldroisys** [comment] 2020-06-25 12:48
Hello @wooj2 

we have implemented follow code snippet:
`    func stateChanged(networkState: ClientNetworkAccessState) {
        print("Status - State changed to: \(networkState)")
        switch networkState {
        case .Offline:
            print("Disconnected")
        case .Online:
            print("Connecting")
        }
    }
`
after disconnecting wifi, we got "Disconnected" state and then connecting wifi we are not able to get "connected" state.

Here is my log file:
connecting
Connecting
Connecting
2020-06-25 17:59:48.704262+0530 AppSync_POC[17510:1079149] Header - Optional("{\"x-amz-date\":\"20200625T122948Z\",\"x-api-key\":\"da2-6di7o4gld5d5tiyhya7jlbnle4\",\"host\":\"w2r274fpk5eivdddnjr3ontgf4.appsync-api.us-east-1.amazonaws.com\"}")
2020-06-25 17:59:48.766215+0530 AppSync_POC[17510:1079146] Connecting to url ...

2020-06-25 17:59:51.083494+0530 AppSync_POC[17510:1079148] WebsocketDidConnect
2020-06-25 17:59:51.083651+0530 AppSync_POC[17510:1079148] WebsocketDidConnect, sending init message...
2020-06-25 17:59:51.083811+0530 AppSync_POC[17510:1079148] Validating connection
2020-06-25 17:59:51.093064+0530 AppSync_POC[17510:1079197] Message type does not need signing - connectionInit("connection_init")
2020-06-25 17:59:51.093656+0530 AppSync_POC[17510:1079197] Websocket write - {"type":"connection_init"}
2020-06-25 17:59:52.026557+0530 AppSync_POC[17510:1079197] WebsocketDidReceiveMessage - {"type":"connection_ack","payload":{"connectionTimeoutMs":300000}}
2020-06-25 17:59:52.038623+0530 AppSync_POC[17510:1079197] WebsocketDidReceiveMessage - {"type":"ka"}
2020-06-25 17:59:52.038688+0530 AppSync_POC[17510:1079148] Start subscription

2020-06-25 17:59:52.038993+0530 AppSync_POC[17510:1079148] Start subscription
2020-06-25 17:59:52.040152+0530 AppSync_POC[17510:1079197] Websocket write - {"id":"122A2C6B-9E54-48FB-8171-18CAF220D95B","payload":{"data":"{\"query\":\"subscription onInsertUpdateAccount {\\n  onInsertUpdateAccount {\\n    __typename\\n    id\\n    AccountName\\n    Address1\\n    City\\n    State\\n    AMName\\n    DMName\\n    RepName\\n    Latitude\\n    Longitude\\n    DistributorId\\n    DistributorName\\n    DistributorAccountId\\n    ClientAccountId\\n    Channel\\n    LicenceType\\n    Banner\\n    SalesType\\n    SocialMediaLinks\\n    ScheduleDays\\n    Contacts\\n  }\\n}\"}","extensions":{"authorization":{"x-amz-date":"20200625T122952Z","x-api-key":"da2-6di7o4gld5d5tiyhya7jlbnle4","host":"w2r274fpk5eivdddnjr3ontgf4.appsync-api.us-east-1.amazonaws.com"}}},"type":"start"}
2020-06-25 17:59:52.041510+0530 AppSync_POC[17510:1079197] Websocket write - {"id":"CD56D0BE-D9D8-487F-A10A-BA95D2C79CD5","payload":{"data":"{\"query\":\"subscription onAddUpdateAccountNote {\\n  onAddUpdateAccountNote {\\n    __typename\\n    Id\\n    UserId\\n    UserName\\n    ClientAccountId\\n    AccountId\\n    Notes\\n    DocumentId\\n    IsActive\\n    CreatedBy\\n    CreatedDate\\n  }\\n}\"}","extensions":{"authorization":{"x-amz-date":"20200625T122952Z","x-api-key":"da2-6di7o4gld5d5tiyhya7jlbnle4","host":"w2r274fpk5eivdddnjr3ontgf4.appsync-api.us-east-1.amazonaws.com"}}},"type":"start"}
2020-06-25 17:59:52.491590+0530 AppSync_POC[17510:1079197] WebsocketDidReceiveMessage - {"id":"122A2C6B-9E54-48FB-8171-18CAF220D95B","type":"start_ack"}
Connected
connected
Connected
Status - State changed to: Offline
Disconnected

Expected Behaviour:
* after connecting wifi we should get connected/Online state.

**Comment by wooj2** [comment] 2020-06-29 17:37
Hi @vishaldroisys ,

The output of your console and the supplied sample code seem to be an exact match of what you have reported in:https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/393

I am closing this ticket as a duplicate.

**Closed by wooj2** 2020-06-29 17:37 UTC
Labels: Question, Requesting Feedback
