### ISSUE TITLE
Got AWSAppsync  issues when integrated in IOS using cocoapods

### ISSUE THREAD

**Issue by svsharsha** [awslabs/aws-mobile-appsync-sdk-ios#412] opened 2020-09-21 12:13 UTC
**Describe the bug**
I used     pod 'AWSAppSync', '~> 2.8.0'
1.'EnumeratedIterator' is deprecated: renamed to 'EnumeratedSequence.Iterator'
2. Redefinition of 'AWSIoTMQTTStatus' like this many in Appsync files.
3.Include of non-modular header inside framework module 'AWSAppSync.AWSAppSync': '/Users/sriharshas/Desktop/StoryPulse_Sep2020/StoryPulse/SP/Pods/Target Support Files/AWSAppSync/AWSAppSync-umbrella.h'
4. Duplicate interface definition for class 'AWSIoTMQTTQueueMessage' etc

I got al to gether 21 errors
**To Reproduce**
1.for integrating appsync i did aws amplify and steps.
2.  pod 'AWSAppSync', '~> 2.8.0'
3.removed all pod files and in terminal , pod install. , all files got deleted
4. Again I added pods including appsync as above and in terminal , pod install. , all files got added.

**Expected behavior**
Ideally my code has to run, but due to appsync errors it dont 
**Screenshots**

**Environment(please complete the following information):**
 - AppSync SDK Version: [ 2.8.0] ->I tried with higher versions also
 - Dependency Manager: [ Cocoapods]
 - Swift Version : [ 4.2]
- Xcode. [11.4.1]

**Device Information (please complete the following information):**
 - Device: [ Simulator]
 - iOS Version: [ipad Air 3G 13]
 - Specific to simulators: can do in any

**Additional context**

#Appsync #Swift #ios

**Comment by svsharsha** [comment] 2020-09-21 12:14
Above issue screen shots.
<img width="1137" alt="Screenshot 2020-09-21 at 5 32 10 PM" src="https://user-images.githubusercontent.com/8224020/93765081-f0192c00-fc31-11ea-87bd-e15cce8b0da9.png">


<img width="573" alt="Screenshot 2020-09-21 at 5 32 37 PM" src="https://user-images.githubusercontent.com/8224020/93765139-03c49280-fc32-11ea-913b-8ff8d64539c6.png">

**Comment by svsharsha** [comment] 2020-09-22 06:54
Can anyone help me out.

I tried with various versions of appsync cocoapod but no luck.

**Comment by svsharsha** [comment] 2020-09-22 09:46
As per my observation below is the main cause for the issue

Include of non-modular header inside framework module 'AWSAppSync.AWSAppSync': '/Users/sriharshas/Desktop/filepath/Pods/Target Support Files/AWSAppSync/AWSAppSync-umbrella.h'

**Comment by ruiguoamz** [comment] 2020-09-23 21:23
Hi, @svsharsha 
Sorry to reply late.

`AWSAppSync` v2.8 is a pretty old version. Any reason still using the old version?

1. I only tried out `pod 'AWSAppSync', '~> 2.8.0'`, but the deprecation of `EnumeratedIterator ` comes from Apple, see [here](https://developer.apple.com/documentation/swift/enumeratediterator).
2. And for other errors like the `Redefinition` one, can you provide more information on that? Thanks

**Comment by svsharsha** [comment] 2020-09-28 01:53
Hi ruiguoamz
I not only tried with 2.8.0 version but also all versions.

I provided more information in above 3 comments.
Can u suggest me a stable version of Appsync which supports Swift 4.2, if not swift 5 versions?

I dont know why this redefinition is coming?Is there any duplicates in pod files?

Thanks for the reply.

**Comment by palpatim** [comment] 2020-09-28 21:28
@svsharsha 

1. To be very clear, you are able to reproduce all of these issues with exactly the same output using the latest version of AppSync (3.1.6)? As @ruiguoamz pointed out the `EnumeratedIterator` issue is a deprecation from Apple that we fixed in a later version of AppSync when we started supporting Swift 5.
1. Besides depending on the `AWSAppSync` pod, what other AWS dependencies and versions are you bringing into your `Podfile`?
1. I see you did a `pod install`; did you update your local cache of the CocoaPods repo first (either by doing `pod install --repo-update` or by doing a `pod repo update` separately before you do the `pod install`)?

**Comment by svsharsha** [comment] 2020-10-07 10:35
Hi palpatim,  please find my answers point wise

1.Initially I used swift 4.2 and got above issues with appsync and then I used swift 5.0 and got same issues again.
ShouldI use only swift 5.0 or can i use 4.2 also ?what do you suggest? 
2. please. check my 2nd post above 
3. I did only pod install, I didn't update your local cache(pod repo update).   ---> I' ll also try this again

thanks for the reply.I'm waiting for longtime

**Comment by palpatim** [comment] 2020-11-04 19:53
Some notes about the pod install logs above:

- The `AWSMobileAnalytics` SDK has been deprecated for close to 2 years and will be removed altogether from the SDK in December. Use [Amplify Analytics](https://docs.amplify.aws/lib/analytics/getting-started/q/platform/ios) or the `AWSPinpoint` SDK for analytics. In my sample, I've replaced this with `AWSPinpoint`.

- The `AWSCognito` SDK ("Cognito Sync") has been deprecated for close to 2 years and will be removed altogether from the SDK in December. You should use AppSync for data synchronization. You can use [Amplify DataStore](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/ios) or the `AWSAppSync` pod (as you're doing) to synchronize data to AppSync. In my sample, I've removed this.

- We recommend either [Amplify Predictions](https://docs.amplify.aws/lib/predictions/getting-started/q/platform/ios) `AWSSageMaker` rather than `AWSMachineLearning`. Note that Amplify Predictions also supports use cases for entity detection which behind the scenes are handled by `AWSRekognition`.

- Generally we recommend using an API Gateway or AppSync resolver rather than direct Lambda invocation from your client app. Putting your Lambda behind APIG or a GraphQL API in AppSync allows you to change the Lambda's business logic and interface without impacting your client.

- If you end up using Amplify, you can use [Amplify Storage](https://docs.amplify.aws/lib/storage/getting-started/q/platform/ios) for upload and download operations, rather than the `AWSS3` pod and its `AWSS3TransferUtility` client

So with all that said, I'm using the following `Podfile` to test:

**Podfile**
```ruby
target 'appsync-pods-test' do
  use_frameworks!
  # Removed AWSCognito
  pod 'AWSAppSync'
  pod 'AWSCognitoIdentityProvider'
  pod 'AWSLambda'
  pod 'AWSS3'
  pod 'AWSRekognition'
  pod 'AWSMachineLearning'
  # Replaces AWSMobileAnalytics
  pod 'AWSPinpoint'
end
```

```bash
% pod --version
1.9.3
% pod install
Analyzing dependencies
Downloading dependencies
Installing AWSAppSync (3.1.10)
Installing AWSCognitoIdentityProvider (2.18.0)
Installing AWSCognitoIdentityProviderASF (2.18.0)
Installing AWSCore (2.18.0)
Installing AWSLambda (2.18.0)
Installing AWSMachineLearning (2.18.0)
Installing AWSPinpoint (2.18.0)
Installing AWSRekognition (2.18.0)
Installing AWSS3 (2.18.0)
Installing AppSyncRealTimeClient (1.4.2)
Installing ReachabilitySwift (5.0.0)
Installing SQLite.swift (0.12.2)
Installing Starscream (3.1.1)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `appsync-pods-test.xcworkspace` for this project from now on.
Pod installation complete! There are 7 dependencies from the Podfile and 13 total pods installed.

[!] Automatically assigning platform `iOS` with version `9.0` on target `appsync-pods-test` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

My app project, created in Xcode 11.4.1:
- Deployment target: iOS 9.0 (modified auto-created project by removing iOS 13-specific references)
- Swift language version: 5.0

**AppDelegate.swift**

```swift
import UIKit

import AWSAppSync
import AWSCognitoIdentityProvider
import AWSCore
import AWSLambda
import AWSMachineLearning
import AWSPinpoint
import AWSRekognition
import AWSS3
```

And I compile without issue on Xcode 11.4.1.

If you continue to have problems, please provide your Podfile, CocoaPods version, and Xcode version so we can troubleshoot.

**Comment by palpatim** [comment] 2020-12-07 21:49
Closing due to inactivity.

**Closed by palpatim** 2020-12-07 21:49 UTC
Labels: build, requesting info
