### ISSUE TITLE
Calling multiple mutations in a row result in memory spikes, and eventually, the app crashes.

### ISSUE THREAD

**Issue by cmastrantono** [awslabs/aws-mobile-appsync-sdk-ios#276] opened 2019-07-09 18:31 UTC
**Describe the bug**
Calling multiple mutations in a row result in memory spikes, and eventually, the app crashes.

**To Reproduce**
1. Run several mutations in a row, without waiting for the callback
2. Mutations must not run in the main thread.
3. Open the Xcode Memory Graph Debugger 
4. Memory starts increasing until it reaches 1.5gb and then it crashes.

If for some reason the mutations end before reaching 1.5GB, eventually the GC will free the memory.

If mutations run on the main thread, behavior improves substantially but it still crashes sometimes.

This works well on 2.11.1, but on 2.12.0+ it starts crashing.

**Expected behavior**
The memory goes up slightly and the app behaves normally.

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.12.0 - 2.13.1
 - Dependency Manager: Cocoapods
 - Swift Version : 5

**Device Information (please complete the following information):**
 - Device: iPhone SE, iPhone XR
 - iOS Version: 12.3.1

**Additional context**
When the mutation runs on the main thread, most of the time behave well. But we've been able to reproduce even in that context.

**Comment by RayPelletier** [comment] 2019-07-09 23:04
"at the expense of a larger number of comparisons"

On further investigation we determined that the memory spikes we were encountering was a consequence of our using a mutation to upload large amounts of floating point sensor data. The method AWSSQLiteNormalizedCache.recordCacheKeyCandidates in combination with AWSSQLiteNormalizedCache.mergeRecords when provided our mutation as input results in an explosion of key candidates.

**Comment by RayPelletier** [comment] 2019-07-10 17:46
Q: Will the use of periods (.) for guessing cache keys be replaced in a future version? (With perhaps code to parse the text to determine exact candidates?)

**Comment by jasonbobier** [comment] 2020-01-20 07:58
Did you ever find a solution to this? I am seeing the same behavior with the latest pods. Thanks!

**Comment by cmastrantono** [comment] 2020-01-20 13:41
Hi Jason,

The last I remember is that it was something related to having multiple
attributes with floating-point. When the library converts the data to JSON
in order to transfer it, the memory crashes... so we ended up modifying our
structure, as modifying the library was not an option by that time.

Hope this helps!

**Comment by jasonbobier** [comment] 2020-01-20 14:33
Would you happen to remember what about the floating point numbers was giving the cache issues? Thanks!

**Comment by RayPelletier** [comment] 2020-01-20 14:34
Hi, Jason. Interesting timing for your question. This week I am revisiting this issue using the new pods. 

With the older pod I tried bypassing the period (.) goofiness by encoding blocks of data as BASE64. While this eliminated the memory spikes/crashes I found that on occasion the AWSTask queue would get wedged. At this point my level of frustration was high enough to warrant punting on the collection of sensor data so I could get V1 of the product out the door.

Now that the product is out I'm going back to see if the newer versions of the pod fixed this. If the problems persists, and perhaps even if they don't, I am going to switch to uploading data by putting files to S3.  These will then processed by a lambda triggered by the put.

**Comment by RayPelletier** [comment] 2020-01-20 14:43
The problem with floating point data are the periods in the string representation. It does not take many as the number of potential cache keys which get generated grows quickly.

**Comment by jasonbobier** [comment] 2020-01-20 14:46
Gotcha... So your appSyncClient.apolloClient?.cacheKeyForObject pointed to a floating point number?

**Comment by RayPelletier** [comment] 2020-01-20 14:50
Not just one. I was uploading CSV data. To check if the problem you are encountering has the same cause as mine you could put breakpoints in the AWSSQLiteNormalizedCache class. (recordCacheKeyCandidates I believe) Here you can examine the number of potential keys which get generated.

**Comment by jasonbobier** [comment] 2020-01-20 17:28
Thanks Ray. I'll put a breakpoint there to see what I see. One place that we are using periods is in our S3Object keys (the file extension).

**Comment by jasonbobier** [comment] 2020-01-21 12:46
I am trying a revert back to AppSync 2.11.1.

**Comment by jasonbobier** [comment] 2020-01-28 09:54
The revert back to 2.11.1 works fine fyi.

**Comment by lawmicha** [comment] 2020-03-06 16:53
hi @jasonbobier 

> The revert back to 2.11.1 works fine fyi.

Thanks, this is a good indication of where we could investigate further on the set of changes that were introduced from 2.11 to 2.12.0. Are you able to confirm it was not working on 2.11's next version, 2.12.0 and not some futher patch version of 2.12.x?

the difference between 2.12.0 and 2.11.0 https://github.com/awslabs/aws-mobile-appsync-sdk-ios/compare/2.11.1...2.12.0

Could you also provide some additional context on your configuration? what does your data model look like? what does your call pattern look like?

If possible, could you try to use the latest SDK version, currently it is at 3.0.2

**Comment by jasonbobier** [comment] 2020-03-06 19:31
I seem to remember that because of dependencies it had to go all the way back to 2.11.1.

The data model is pretty straight forward users, groups, media file information including the S3 region, bucket, and key. The calls are just graphql calls to update the media metadata when users add a piece of media.

I'll have to wait until I get moment to update to 3.0.2. The issue definitely seems to be in the new sql lite code. (I can't remember what version, but there was a move away from the sqlite pod that is used in 2.11.1.

**Comment by fila** [comment] 2020-06-04 13:15
Had the very same issue using AWSAppSync 2.14.0: the memory consumption rose quickly and the app got killed at the point when it was consuming 1.5 GB.
The difference was that it was a single mutation with a massive array of location data.

Fixed with rolling back to 2.11.1.

**Comment by palpatim** [comment] 2020-11-04 22:42
We believe this is a duplicate of https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/173: fast growth of the local cache because of the cache key strategy the underlying persistence mechanism uses.

Regarding reverting to 2.11.1 would have any impact on that: what might be happening is that apps on 2.11.1 that don't see the memory growth are actually getting SQLite errors preventing the persistence tables from being created in the first place, resulting in everything being a cache miss. The upgrade fixes that bug and causes the app to start using the cache, which would then cause the memory growth.

Because of our assessment that this is a dupe of #173, we're not inclined to fix the problem at this time--please see https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/173#issuecomment-721992824 for more detail.

**Closed by palpatim** 2020-11-04 22:42 UTC
