### ISSUE TITLE
Fetch request Freeze after network reconnection

### ISSUE THREAD

**Issue by skatolyk** [awslabs/aws-mobile-appsync-sdk-ios#311] opened 2019-10-30 15:19 UTC
**Describe the bug**
Get freeze after I'm trying to fetch some info right after network reconnection

**To Reproduce**
1. Turn off any network connection;
2. Turn on connection;
3. Try to fetch some info.

**Expected behavior**
No freeze. As response I'm waiting or success or failure but get nothing.

**Environment:**
- AWSAppSync (2.14.3):
    - AWSCore (~> 2.11.0)
    - ReachabilitySwift (= 4.3.0)
    - SQLite.swift (= 0.11.6)
  - AWSCognito (2.11.1):
    - AWSCore (= 2.11.1)
  - AWSCognitoAuth (2.11.1):
    - AWSCognitoIdentityProviderASF (= 1.0.1)
  - AWSCognitoIdentityProvider (2.11.1):
    - AWSCognitoIdentityProviderASF (= 1.0.1)
    - AWSCore (= 2.11.1)
  - AWSCognitoIdentityProviderASF (1.0.1)
  - AWSCore (2.11.1)

 - Dependency Manager: Cocoapods;
 - Swift Version: 5.0.

**Device Information:**
 - Device: Any iPhone;
 - iOS Version: iOS 13.

**Logs:**
2019-10-30 16:59:48.940393+0200 **************[633:83005] OSStatus error: [-25299] Security error has occurred.
2019-10-30 16:59:51.499921+0200 **************[633:83005] OSStatus error: [-25299] Security error has occurred.
2019-10-30 16:59:51.503528+0200 **************[633:83008] OSStatus error: [-25299] Security error has occurred.
Authentication failed. fetch
2019-10-30 17:00:11.804813+0200 **************[633:83933] [] tcp_output [C146.1:3] flags=[R.] seq=2534462686, ack=4233513660, win=1024 state=CLOSED rcv_nxt=4233513660, snd_una=2534462608
2019-10-30 17:00:21.104014+0200 **************[633:83375] [] tcp_output [C139.1:3] flags=[R.] seq=3950132137, ack=1483439370, win=1024 state=CLOSED rcv_nxt=1483439370, snd_una=3950132059
2019-10-30 17:00:22.273710+0200 **************[633:83934] [] tcp_output [C148.1:3] flags=[R.] seq=118770639, ack=1976592444, win=1024 state=CLOSED rcv_nxt=1976592444, snd_una=118770561
2019-10-30 17:00:27.166621+0200 **************[633:83933] [] tcp_output [C137.1:3] flags=[R.] seq=1120885715, ack=1777695944, win=1024 state=CLOSED rcv_nxt=1777695944, snd_una=1120885637
2019-10-30 17:00:41.313693+0200 **************[633:83933] [] tcp_output [C152.1:3] flags=[R.] seq=159662233, ack=523174815, win=1024 state=CLOSED rcv_nxt=523174815, snd_una=159662106
2019-10-30 17:00:51.594058+0200 **************[633:84063] [] tcp_input [C328.1:3] flags=[R] seq=407397159, ack=0, win=0 state=LAST_ACK rcv_nxt=407397159, snd_una=2914117484
2019-10-30 17:00:51.595359+0200 **************[633:84063] [] tcp_input [C328.1:3] flags=[R] seq=407397159, ack=0, win=0 state=CLOSED rcv_nxt=407397159, snd_una=2914117484
2019-10-30 17:00:51.595510+0200 **************[633:84063] [] tcp_input [C328.1:3] flags=[R] seq=407397159, ack=0, win=0 state=CLOSED rcv_nxt=407397159, snd_una=2914117484
2019-10-30 17:00:52.543144+0200 **************[633:84063] [] tcp_input [C330.1:3] flags=[R] seq=1988549446, ack=0, win=0 state=LAST_ACK rcv_nxt=1988549446, snd_una=971901821
2019-10-30 17:00:52.545838+0200 **************[633:84063] [] tcp_input [C330.1:3] flags=[R] seq=1988549446, ack=0, win=0 state=CLOSED rcv_nxt=1988549446, snd_una=971901821
2019-10-30 17:01:35.310420+0200 **************[633:83637] [] nw_resolver_start_query_timer_block_invoke [C464] Query fired: did not receive both families in time for cognito-identity.us-east-1.amazonaws.com:443
2019-10-30 17:02:31.331665+0200 **************[633:83621] [] nw_resolver_start_query_timer_block_invoke [C530] Query fired: did not receive both families in time for nvlyof46z5gmhlfddti6r2bmb4.appsync-api.us-east-1.amazonaws.com:443
2019-10-30 17:10:26.759225+0200 **************[633:83933] [] nw_resolver_start_query_timer_block_invoke [C1102] Query fired: did not receive both families in time for nvlyof46z5gmhlfddti6r2bmb4.appsync-api.us-east-1.amazonaws.com:443

**Comment by lawmicha** [comment] 2019-11-04 21:32
Hi @skatolyk 

Thanks for the question, is this reproducible at all times? and how long do you have to wait until you get a response back (whether it was completed or failed). it looks like there's a log line that says `Authentication failed. fetch` so it may be trying to reauthenticate. if it successfully re-authenticates then the fetch should go through and then you should see a completed event. If it fails, then you should check that failure case and prompt the user to sign in again.

**Comment by skatolyk** [comment] 2019-11-08 20:46
@lawmicha I've resolved this issue by app side. Thanks.

**Comment by lawmicha** [comment] 2019-11-11 19:27
HI @skatolyk  Glad you were able to fix the issue. Closing now. Feel free to update here with what the problem and fix was! Thanks

**Closed by lawmicha** 2019-11-11 19:27 UTC

**Comment by mnowackifm** [comment] 2020-08-24 09:36
@skatolyk What was the cause of the issue in your app? Was that related to `NetworkExtension`?

**Comment by ajith8291** [comment] 2020-09-10 09:44
Hi @skatolyk, How did you solve this issue. Can you please tell me, I am also facing same problem.

**Comment by skatolyk** [comment] 2020-09-10 15:49
@ajith8291 @mnowackifm Actually I don't remember exactly as I've finished that project more then half year ago. Only I remember the reason was in some completion handling after network reconnection. Not related to library
