### ISSUE TITLE
AWS Amplify SDK IOS - Subscription When App Remains Idle for a Long Time

### ISSUE THREAD

**Issue by howardevans21** [awslabs/aws-mobile-appsync-sdk-ios#403] opened 2020-07-22 18:46 UTC
I've followed the ios SDK for AWS Amplify using version with AWSMobileClient. 

The IOS app successfully initializes the subscription and it works for about 20 minutes. 

After the ios App remains idle for over 20 minutes, the subscription does not get to the following block of code to load the table view cell. 

// Update Cache Data
  try transaction?.write(object: chatData, withKey: matchUser.matchData.chatRoomId!) 

 self.loadMessages(policy: .returnCacheDataElseFetch)

So loadMessages function never gets called because transaction.write code does not get to the point to get to the next block of code. 

It works initially for about 20 minutes, then it stops. 

Thanks

**Comment by palpatim** [comment] 2020-07-28 23:02
Dupe of #396, tracking there.

**Closed by palpatim** 2020-07-28 23:02 UTC
Labels: Bug, Duplicate

**Comment by palpatim** [comment] 2020-07-31 23:18
Released on [3.1.4](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/releases/tag/3.1.4).
