### ISSUE TITLE
Store WithReadWriteTransaction updates do not persist after app close.

### ISSUE THREAD

**Issue by w0mba7** [awslabs/aws-mobile-appsync-sdk-ios#234] opened 2019-04-16 17:43 UTC
**Describe the bug**
Writing to the cache directly doesn't update the persistent store and does not live through app shutdown.  The cache is functioning because I run another query and get results from the server then shut down the app, and then see those results using a query with the .returnCacheDataDontFetch policy. 

**To Reproduce**
1) Get Data from outside source
2) And to cache using ApolloClient.Store.withinReadWriteTransaction.
3) Run Query that you added data for using .returnCacheDataDontFetch cache policy.
4) Verify Results
5) Force Quit App
6) Run Query from Step 3
7) Results Not Found. 

**Expected behavior**
I expect that updating the cache directly would also right to the persistent cache. 

**Screenshots**

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.10.4
 - Dependency Manager: Carthage
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhoneX and Simulators
 - iOS Version: 12.2
 - Specific to simulators: No

**Additional context**

**Comment by rohandubal** [comment] 2019-04-18 22:36
Hello @w0mba7 

Could you please answer these questions so that we could help you better?

- Can you provide a code snippet using which we can reproduce this issue?
- Are you checking for any errors which could have happened during the write?

Thanks,
Rohan

**Comment by w0mba7** [comment] 2019-04-19 18:54
Here is the code that i have for writing updating the cache.   I didn't see any errors in the console log and I can use the results else were in the app, they are just lost when the app quits.  Is there somewhere specific I should be checking for the write erros?
`
let t = self.appSyncClient?.store?.withinReadWriteTransaction { transaction in
            try transaction.update(query: AllProductsQuery())
                        { (data: inout AllProductsQuery.Data) in
                            data.allProducts = []
                            let cacheItems = list.compactMap({ (item) -> AllProductsQuery.Data.AllProduct? in
                                if let id = item.id,
                                    let title = item.title {
                                    return AllProductsQuery.Data.AllProduct.init(id: id, title: title)
                                } else {
                                    return nil
                                }
                            })
                            data.allProducts?.append(contentsOf: cacheItems)
                        }
                    }
`

**Comment by palpatim** [comment] 2019-04-22 14:42
@w0mba7 

We're aware of an [issue with the persistent cache](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/211) for apps built using Xcode 10.2. Can you verify the version of Xcode you're using? (Since you specify iOS 12.2, I'm assuming it's Xcode 10.2 or 10.2.1, but I'd like to confirm.)

**Comment by w0mba7** [comment] 2019-04-22 14:59
Yes I am using Xcode 10.2.1

**Comment by palpatim** [comment] 2019-04-22 16:22
Thanks for the update. I believe this will be fixed when we update to SQLite.swift 0.11.6. I'll update this issue once we have that released.

**Comment by w0mba7** [comment] 2019-04-22 18:04
I just added SQLite 11.6 as a direct dependency in Carthage and I was able to force close the app and relaunch with the data.

**Comment by palpatim** [comment] 2019-04-22 21:02
That's great to hear. I'm going to leave this issue open until we resolve the SQLite update in the main codebase.

**Comment by palpatim** [comment] 2019-04-24 13:25
This is fixed in [2.12.0](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/releases/tag/2.12.0). Please comment on that issue if you continue to see problems.

**Closed by palpatim** 2019-04-24 13:25 UTC
Labels: AppSync, Bug, Requesting Feedback
