### ISSUE TITLE
2.12+ of AppSync consumes all of the app memory and then crashes

### ISSUE THREAD

**Issue by jasonbobier** [awslabs/aws-mobile-appsync-sdk-ios#329] opened 2020-01-28 09:58 UTC
I'm putting this here to bump up #276 because it looks like it is languishing. I'm seeing this same behavior and have had to revert to 2.11.1. I'm not using large numbers of floating points, but several of the fields that I'm storing do have periods. I am especially seeing this when I upload large pieces of multimedia to S3 and then storing the region/bucket/key using a graphql mutation. Note that the key field here does have a period because it contains the file extension of the media file that I'm uploading.

Thanks

**Comment by lawmicha** [comment] 2020-03-06 16:56
Could you clarify what you mean by `upload large pieces of multimedia to S3 and then storing the region/bucket/key using a graphql mutation` Are you using the AppSync feature with s3 complex objects or do you mean you are using something like TransferUtility to upload to S3 and on callback, store the key as part of your mutation data?

**Comment by jasonbobier** [comment] 2020-03-06 19:21
No, I'm using transfer utility. But it seemed to be worse with the multipart upload enabled.

**Comment by palpatim** [comment] 2020-11-05 16:07
Closing as dupe of #276, which is itself a dupe of #173. See those issues for more discussion.

**Closed by palpatim** 2020-11-05 16:07 UTC
Labels: bug
