### ISSUE TITLE
AWSPerformMutationOperation causes high CPU usage and freezes UI

### ISSUE THREAD

**Issue by btn52396** [awslabs/aws-mobile-appsync-sdk-ios#173] opened 2019-02-08 21:40 UTC
**Describe the bug**
AWSPerformMutationOperation uses an unnecessary amount of CPU, causing the UI to freeze and sometimes crashes the program if too many mutations are performed in succession.  

**To Reproduce**
1. Perform many mutations in rapid succession. I.e send 1000 mutations back to back.
2. Look at CPU usage. You will find that the CPU will gradually grow higher and higher over the minute or two it takes to perform all the mutations. The UI will start to suffer considerably as well

**Expected behavior**
AWSPerformOfflineMutationOperation on the other hand works as expected. Very low CPU usage, UI works without a problem. AWSPerformOfflineMutationOperation only gets called in loadMutations() which in turn only gets called when appSyncClient is initialized. For my temporary solution, I've modified the add function in the AWSPerformMutationQueue class, replacing AWSPerformMutationOperation with AWSPerformOfflineMutationOperation. I suspect it has something to do with AWSPerformMutationOperation's use of mutationConflictHandler or mutationResultHandler but I haven't had a chance to investigate further.

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.9.2
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: iPhone 8
 - iOS Version: 12
 - Specific to simulators: No

**Comment by palpatim** [comment] 2019-02-08 21:45
@btn52396 

Thanks so much for diving into this! I've got a bit more work to get the Mutation Queue where I want it, and this will definitely help target my efforts.

**Comment by btn52396** [comment] 2019-02-11 05:36
@palpatim 
Glad to help :) let me know if you need help reproducing and I'll send some code over

**Comment by palpatim** [comment] 2019-02-21 17:42
@btn52396 

I just realized I never responded to your offer! If you have some repro code, I'd love to have that as a basis for tests against this behavior.

**Comment by palpatim** [comment] 2019-02-21 22:35
I've made a change locally (that I'll push in a PR soon):

- `AWSAppSyncClient.perform(mutation:queue:optimisticUpdate:conflictResolutionBlock:resultHandler:)` now properly invokes its result handler callbacks on the supplied `queue` instead of always using `DispatchQueue.main`
- Added mutation queue performance tests to validate the perform -> persist -> response lifecycle. 

My observation is that performance on that is quite good on my laptop, even with 1000 mutations being concurrently performed, taking on the order of ~3 seconds to perform, persist and invoke callbacks for 1000 mutations.

I don't *think* the bug fix to invoke the result handler on the specified queue is the root cause of the issue you're seeing, since I have tested using the main queue and see similar performance characteristics.

It may be that the [change to separate the mutation queue from the records cache](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/commit/64bd6f2afa3aa8569b35000426b06240f52f7132) reduced DB contention enough to speed this up (which I'm mimicking in the unit test by only doing mutation queue testing) or it may be that the performance is bottlenecking at some other point in the system.

My plan is to add performance tests for mutations with a meaningful payload (as opposed to the "minimal payload" tests that I'm doing now) as well as an integration test to validate performance when we get the network stack into the mix.

But as it stands right now, I don't have good repro for this case on the latest AppSync code.

**Comment by btn52396** [comment] 2019-02-22 09:44
Here you go https://github.com/btn52396/aws-mobile-appsync-events-starter-ios

It's a fork of the events sample app. Just put in your api info and run it. Press the add button on the top right to do the performance test.

Here's what you can expect to see: https://prnt.sc/mojz2c

Let me know if you need anything else. I can offer a PR of my temporary solution as well.

**Comment by palpatim** [comment] 2019-02-22 15:36
Thanks, I'll take a look!

**Comment by bingosabi** [comment] 2019-02-25 23:17
Thanks for the work on this! 

I have also traced a ~5 second freeze in my App's UI to this same issue.  (AWSPerformMutationQueue using the .main queue, even though I specified a different handler queue.)   My app freeze only appears to happen on the first mutation call, so I suspect that the Sqlite serialQueue has some initialization work going on it which causes the call to save the mutation to linger...  meanwhile the main thread waits.   

any ETA on the PR for your commit @palpatim?

**Comment by palpatim** [comment] 2019-02-26 00:18
We're reviewing the "respect main queue" change now: #188

I've run @btn52396's sample app, but so far I'm not seeing significant performance impacts or memory growth running on sim--certainly nothing like the graph above.

My next steps will be to build this onto a test device & try it there to try and localize the performance problems. I do see some memory growth, but nothing that I haven't been able to rationalize. But I may change my tune after more exploration.

**Comment by bingosabi** [comment] 2019-02-26 16:11
I suppose my bug description is slightly different than @btn52396 's, even though I believe that @palpatim's PR will resolve it.   I would word it:   "*AWSPerformMutationOperation freezes UI if other queries are reading data from cache.*"  which is only half related to the issue @btn52396 is describing.   @btn52396's bug really describes 2 distinct issues: 1. Excessive CPU on multiple mutations, 2. Blocking the main thread.  

I have 4 queries reading from cache on app startup on various queues, and then my single mutation gets launched on a background queue once Apple returns the APNS token to set it on the server...  But because mutations currently get shuffled back to the main thread, it's waiting to execute the mutation on the serial Sqlite thread which already has a backlog from the read queries.  This freezes the UI. 

I'm concerned from your next steps comment that the PR will get closed if you don't see the performance issue that @btn52396 described in his sample app, even though if _anything_ is bogging down the Sqlite queue, a mutation execution will block the UI the way the current code is structured. 

If you'd like I can try to find some cycles to mod the sample app to demonstrate this, but I probably wont be able to get to it for a few days.

**Comment by palpatim** [comment] 2019-02-26 18:07
@bingosabi 

The main queue PR was just approved and merged. :) The performance issue is what I'm specifically referring to not being able to replicate.

Thanks for the description of your use case, that might help target the investigation as well. Of course, if you are able to repro in a sample app, that's always welcome too! but I'll be diving into this over the next couple of days.

**Comment by bingosabi** [comment] 2019-02-27 01:49
@palpatim

Thanks for that!
 
I'll try to get the sample app server side setup at some-point, as that's the main thing keeping me from providing a quick sample which shows the issue.    But just have a few projects with deadlines currently.

**Comment by palpatim** [comment] 2019-02-27 14:40
@bingosabi 

The queue fix is released on 2.10.2. I'll update this thread when I have info on the performance investigation.

**Comment by palpatim** [comment] 2019-02-28 15:22
So far, I don't have any conclusive updates. I've determined that the performance and memory usage issues are definitely associated with use of the SQLite persistence cache--specifically during the `merge` phase where a successful mutation result is merged into the Apollo normalized cache. 

One thing I noticed is that the `MUTATION_ROOT` cache record is enormous, since it stores the entire operation, plus arguments, for every mutation it performs. For the stress test scenario, that means each mutation is adding ~2KB to the `MUTATION_ROOT` cache record. During merges, we read that record from SQLite, deserialize it, merge in the new mutation data, re-serialize it, and write it to disk. That *might* be accounting for the issues we're seeing.

However, I'm continuing my investigation and will update as I get more info.

**Comment by btn52396** [comment] 2019-03-01 06:25
So you were able to successfully reproduce the performance issue?

**Comment by palpatim** [comment] 2019-03-01 15:40
I do see high CPU usage, which I would expect to translate to bad UI performance if I were running on a real device (I don't notice any particular jankiness since I'm currently testing on SIM, which in my experience tends to have better UI performance). Still diving into the `merge` method.

**Comment by airstance** [comment] 2019-04-05 18:12
Have you tried adding a transaction around the SQL statements?  #140

**Comment by btn52396** [comment] 2019-04-05 20:09
Yes, that was the first thing I tried. There was no noticeable difference.

**Comment by btn52396** [comment] 2019-04-24 02:21
The last update has inadvertently fixed this issue.

**Comment by btn52396** [comment] 2019-05-01 05:02
I've spoken too soon. Not sure why it worked last time. Just tested again today with the most current version and the problem appeared again. I will be reverting to my fork in the meantime

**Comment by palpatim** [comment] 2019-06-06 18:18
I'm reasonably sure at this point that the problem is with the strategy the SQLiteNormalizedCache uses for its `merge`. The current cache strategy causes `QUERY_ROOT` to grow unbounded. Eventually, the app is reading multiple megs of data for each merge of a query result.

This is going to require a rethink of our local persistence layer. For now, we don't have a good workaround other than using the "make everything an `AWSPerformOfflineMutationOperation `" strategy @btn52396 outlined in the original post. That strategy bypasses the `merge` step (which has implications for downstream cache behavior), which means this issue won't get triggered.

We're exploring options and will update this thread when we have more information.

**Comment by afterthought** [comment] 2019-06-21 14:06
This is critical for us.... We have an internal enterprise app in production right now. We need to update the SDK, but in our testing so far we see UI freezing pretty consistently with moderate data and mutations. How is this not a major issue for most everyone?

**Comment by bingosabi** [comment] 2019-10-02 21:08
@afterthought probably too late to be helpful, but I just got back to this issue, having seen it was reopened, and encountering a similar behavior to yours.   I realized I wasn't putting my mutations on a background queue via the second argument to AppSyncClient.perform(mutation:, queue:... )  which seemed to be my latest main thread blocker.  (it defaults to DispatchQueue.main)  Switching it to serial background crew definitely alleviated lots of my main thread blocks from this issue.     The other thing that I'm resorting to is periodically clearing the cache to get around the unbounded issues @palpatim described above after some number of mutations.

**Comment by torigeorge** [comment] 2019-10-24 15:17
Experiencing same issue to a T. @afterthought @palpatim Did you get this fixed?

**Comment by bingosabi** [comment] 2020-02-05 16:30
@palpatim Any update on this?    I understood in June that a major re-architecture was going to be needed to fix this, but haven't heard anything since.    We continue to have performance issues on cache read after just a few mutations are made.    I'm at the point that without a definitive timeline I'm going to abandon the AppSync SDK client side and just talk directly to the graphql endpoint using either Apollo or rest.

**Comment by palpatim** [comment] 2020-11-04 21:47
At this stage, we're not inclined to take any action on this issue. We considered a few options, including a fundamental rework of the underlying caching strategy, but nothing met the bar for risk vs. reward: a rewrite of that complexity would invariably introduce new bugs, change behaviors, or remove existing functionality (such as the very object graph persistence that appears to trigger this issue).

For apps impacted by this issue, our guidance remains the same: you can either forego local persistence altogether by using the "make everything an `AWSPerformOfflineMutationOperation` " strategy @btn52396 outlined in the original post, or by periodically clearing the cache to remove the exploding cache keys.

If your use case allows it, you can also consider Amplify DataStore as an alternative. It's a rethink of how we handle app data: local-first writes, local-only reads, and transparent synchronization to the cloud. It's not without tradeoffs: DataStore's model-based view of the world doesn't transparently handle object graphs at present, so model relationships have to be loaded & persisted manually. Complex custom queries are possible, but require crafting custom GraphQL documents as opposed to deeply nested types being code-generated. And DataStore currently doesn't support complex object handling (that is, uploading files to S3 alongside your GraphQL mutation). However, if your app doesn't rely on those features, then please consider DataStore. If it does, keep an eye on DataStore anyway, because we're working to handle the use cases and close the gaps with the AppSync client.

**Closed by palpatim** 2020-11-04 21:47 UTC
Labels: bug, pending investigation
